version: '3.9'
services:
  app:
    container_name: myapp
    image: ziggle/go-http:v0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_OPTS: 13
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - VERSION=${VERSION}
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.16.107.102:3306/wdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=3
    ports:
      - 19090:9090
